# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mctstrackerrn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mctstrackerrn
  pod 'React', :path => '../node_modules/react-native', subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'BatchedBridge'
  ]
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
  end
end
